plugins {
    id "com.android.application" version "8.11.1" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://storage.googleapis.com/download.flutter.io'
        }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    afterEvaluate { project ->
        if (project.hasProperty('android')) {
            if (project.android.namespace == null) {
                project.android.namespace = "com.example.${project.name}"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}