allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    plugins.withId("com.android.library") {
        android {
            if (namespace == null) {
                namespace = "com.example.${project.name}"
            }
        }
    }
    plugins.withId("com.android.application") {
        android {
            if (namespace == null) {
                namespace = "com.example.${project.name}"
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}